services:
  api:
    build:
      context: .
      dockerfile: API/DockerFile
    ports:
      - "5000:8080"
    environment:
      - Jwt__Key=super-secret-key-minimum-32-characters-long
      - Jwt__Issuer=UrlShortener
      - Jwt__Audience=UrlShortener
      - Jwt__ExpiryDays=7
      - ConnectionStrings__Default=Host=db;Port=5432;Database=urlshortener;Username=postgres;Password=postgres
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    container_name: urlshortener_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urlshortener
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: urlshortener_redis
    ports:
      - "6379:6379"

volumes:
  pgdata: